blank_issues_enabled: false
contact_links:
  - name: Security problem
    url: https://github.com/Iliya-Valizadeh/.github/blob/main/SECURITY.md
    about: Do not report security problems in a public issue. Read this policy first.
